version: "2"

services:
  web:
    container_name: web_app
    build: ./
    restart: always
    command: gunicorn app:app -w 2 --threads 4 -k gevent -b 0.0.0.0:8080 --log-level debug
    networks:
      - backend

  nginx:
    container_name: web_nginx
    build: ./nginx/
    expose:
      - '8001'
    ports:
      - '8001:8001'
    networks:
      - backend

networks:
  backend:
    driver: bridge